apiVersion: v1
kind: Service
metadata:
  name: httpd
  namespace: default
spec:
  type: {{ .Values.service.type }}
  selector:
    app: httpd-app
  ports:
    - port: {{ .Values.service.port }}
      targetPort: 80
      
