apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-volume2
  labels:
    type: local
spec:
  storageClassName: default
  capacity:
    storage: 350Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/kamil/var"
